#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.6.7 (standalone edition) on Fri Jun 21 21:01:46 2013
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class myFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: myFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.mainframe_statusbar = self.CreateStatusBar(1, wx.ST_SIZEGRIP)
        self.pnlmain = wx.Panel(self, wx.ID_ANY)
        self.window_1 = wx.SplitterWindow(self.pnlmain, wx.ID_ANY, style=wx.SP_3DBORDER | wx.SP_BORDER)
        self.wdTitle = wx.ScrolledWindow(self.window_1, wx.ID_ANY, style=wx.STATIC_BORDER | wx.TAB_TRAVERSAL)
        self.label1 = wx.StaticText(self.wdTitle, wx.ID_ANY, "label1")
        self.label2 = wx.StaticText(self.wdTitle, wx.ID_ANY, "label2")
        self.label3 = wx.StaticText(self.wdTitle, wx.ID_ANY, "label3")
        self.label4 = wx.StaticText(self.wdTitle, wx.ID_ANY, "label4")
        self.label5 = wx.StaticText(self.wdTitle, wx.ID_ANY, "label5")
        self.label6 = wx.StaticText(self.wdTitle, wx.ID_ANY, "label6")
        self.label7 = wx.StaticText(self.wdTitle, wx.ID_ANY, "label7")
        self.label8 = wx.StaticText(self.wdTitle, wx.ID_ANY, "label8")
        self.label9 = wx.StaticText(self.wdTitle, wx.ID_ANY, "label9")
        self.label10 = wx.StaticText(self.wdTitle, wx.ID_ANY, "label10")
        self.label11 = wx.StaticText(self.wdTitle, wx.ID_ANY, "label11")
        self.label12 = wx.StaticText(self.wdTitle, wx.ID_ANY, "label12")
        self.label13 = wx.StaticText(self.wdTitle, wx.ID_ANY, "label13")
        self.label14 = wx.StaticText(self.wdTitle, wx.ID_ANY, "label14")
        self.label15 = wx.StaticText(self.wdTitle, wx.ID_ANY, "label15")
        self.label16 = wx.StaticText(self.wdTitle, wx.ID_ANY, "label16")
        self.label17 = wx.StaticText(self.wdTitle, wx.ID_ANY, "label17")
        self.label18 = wx.StaticText(self.wdTitle, wx.ID_ANY, "label18")
        self.label19 = wx.StaticText(self.wdTitle, wx.ID_ANY, "label19")
        self.label20 = wx.StaticText(self.wdTitle, wx.ID_ANY, "label20")
        self.label21 = wx.StaticText(self.wdTitle, wx.ID_ANY, "label21")
        self.label22 = wx.StaticText(self.wdTitle, wx.ID_ANY, "label22")
        self.label23 = wx.StaticText(self.wdTitle, wx.ID_ANY, "label24")
        self.label24 = wx.StaticText(self.wdTitle, wx.ID_ANY, "label24")
        self.label25 = wx.StaticText(self.wdTitle, wx.ID_ANY, "label25")
        self.label26 = wx.StaticText(self.wdTitle, wx.ID_ANY, "label26")
        self.label27 = wx.StaticText(self.wdTitle, wx.ID_ANY, "label27")
        self.label28 = wx.StaticText(self.wdTitle, wx.ID_ANY, "label28")
        self.label29 = wx.StaticText(self.wdTitle, wx.ID_ANY, "label29")
        self.label30 = wx.StaticText(self.wdTitle, wx.ID_ANY, "label30")
        self.label31 = wx.StaticText(self.wdTitle, wx.ID_ANY, "label31")
        self.label32 = wx.StaticText(self.wdTitle, wx.ID_ANY, "label32")
        self.wdCanvas = wx.ScrolledWindow(self.window_1, wx.ID_ANY, style=wx.STATIC_BORDER | wx.TAB_TRAVERSAL)
        self.pnlCanvas = wx.Panel(self.wdCanvas, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: myFrame.__set_properties
        self.SetTitle("Tool")
        self.mainframe_statusbar.SetStatusWidths([-1])
        # statusbar fields
        mainframe_statusbar_fields = ["mainframe_statusbar"]
        for i in range(len(mainframe_statusbar_fields)):
            self.mainframe_statusbar.SetStatusText(mainframe_statusbar_fields[i], i)
        self.label1.SetMinSize((-1, 15))
        self.label2.SetMinSize((-1, 15))
        self.wdTitle.SetScrollRate(1, 1)
        self.pnlCanvas.SetMinSize((1000, 400))
        self.wdCanvas.SetScrollRate(1, 1)
        self.pnlmain.SetMinSize((850, 520))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: myFrame.__do_layout
        sizer1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer3 = wx.BoxSizer(wx.VERTICAL)
        sizer3.Add(self.label1, 0, wx.EXPAND, 0)
        sizer3.Add(self.label2, 0, wx.EXPAND, 0)
        sizer3.Add(self.label3, 0, wx.EXPAND, 0)
        sizer3.Add(self.label4, 0, wx.EXPAND, 0)
        sizer3.Add(self.label5, 0, wx.EXPAND, 0)
        sizer3.Add(self.label6, 0, wx.EXPAND, 0)
        sizer3.Add(self.label7, 0, wx.EXPAND, 0)
        sizer3.Add(self.label8, 0, wx.EXPAND, 0)
        sizer3.Add(self.label9, 0, wx.EXPAND, 0)
        sizer3.Add(self.label10, 0, wx.EXPAND, 0)
        sizer3.Add(self.label11, 0, wx.EXPAND, 0)
        sizer3.Add(self.label12, 0, wx.EXPAND, 0)
        sizer3.Add(self.label13, 0, wx.EXPAND, 0)
        sizer3.Add(self.label14, 0, wx.EXPAND, 0)
        sizer3.Add(self.label15, 0, wx.EXPAND, 0)
        sizer3.Add(self.label16, 0, wx.EXPAND, 0)
        sizer3.Add(self.label17, 0, wx.EXPAND, 0)
        sizer3.Add(self.label18, 0, wx.EXPAND, 0)
        sizer3.Add(self.label19, 0, wx.EXPAND, 0)
        sizer3.Add(self.label20, 0, wx.EXPAND, 0)
        sizer3.Add(self.label21, 0, wx.EXPAND, 0)
        sizer3.Add(self.label22, 0, wx.EXPAND, 0)
        sizer3.Add(self.label23, 0, wx.EXPAND, 0)
        sizer3.Add(self.label24, 0, wx.EXPAND, 0)
        sizer3.Add(self.label25, 0, wx.EXPAND, 0)
        sizer3.Add(self.label26, 0, wx.EXPAND, 0)
        sizer3.Add(self.label27, 0, wx.EXPAND, 0)
        sizer3.Add(self.label28, 0, wx.EXPAND, 0)
        sizer3.Add(self.label29, 0, wx.EXPAND, 0)
        sizer3.Add(self.label30, 0, wx.EXPAND, 0)
        sizer3.Add(self.label31, 0, wx.EXPAND, 0)
        sizer3.Add(self.label32, 0, wx.EXPAND, 0)
        self.wdTitle.SetSizer(sizer3)
        sizer4.Add(self.pnlCanvas, 1, wx.SHAPED, 0)
        self.wdCanvas.SetSizer(sizer4)
        self.window_1.SplitVertically(self.wdTitle, self.wdCanvas, 70)
        sizer2.Add(self.window_1, 1, wx.EXPAND, 0)
        self.pnlmain.SetSizer(sizer2)
        sizer1.Add(self.pnlmain, 1, wx.EXPAND, 0)
        self.SetSizer(sizer1)
        sizer1.Fit(self)
        self.Layout()
        self.Centre()
        # end wxGlade

# end of class myFrame
class MyApp(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        mainframe = myFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(mainframe)
        mainframe.Show()
        return 1

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()