#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.6.7 (standalone edition) on Mon Jun 17 21:22:06 2013
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class myFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: myFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.mainframe_statusbar = self.CreateStatusBar(1, 0)
        self.scrollwin = wx.ScrolledWindow(self, wx.ID_ANY, style=wx.TAB_TRAVERSAL)
        self.pnlTitle = wx.Panel(self.scrollwin, wx.ID_ANY)
        self.label1 = wx.StaticText(self.pnlTitle, wx.ID_ANY, "label1")
        self.label2 = wx.StaticText(self.pnlTitle, wx.ID_ANY, "label2")
        self.label3 = wx.StaticText(self.pnlTitle, wx.ID_ANY, "label3")
        self.label4 = wx.StaticText(self.pnlTitle, wx.ID_ANY, "label4")
        self.label5 = wx.StaticText(self.pnlTitle, wx.ID_ANY, "label5")
        self.label6 = wx.StaticText(self.pnlTitle, wx.ID_ANY, "label6")
        self.label7 = wx.StaticText(self.pnlTitle, wx.ID_ANY, "label7")
        self.label8 = wx.StaticText(self.pnlTitle, wx.ID_ANY, "label8")
        self.label9 = wx.StaticText(self.pnlTitle, wx.ID_ANY, "label9")
        self.label10 = wx.StaticText(self.pnlTitle, wx.ID_ANY, "label10")
        self.label11 = wx.StaticText(self.pnlTitle, wx.ID_ANY, "label11")
        self.label12 = wx.StaticText(self.pnlTitle, wx.ID_ANY, "label12")
        self.label13 = wx.StaticText(self.pnlTitle, wx.ID_ANY, "label13")
        self.label14 = wx.StaticText(self.pnlTitle, wx.ID_ANY, "label14")
        self.label15 = wx.StaticText(self.pnlTitle, wx.ID_ANY, "label15")
        self.label16 = wx.StaticText(self.pnlTitle, wx.ID_ANY, "label16")
        self.label17 = wx.StaticText(self.pnlTitle, wx.ID_ANY, "label17")
        self.label18 = wx.StaticText(self.pnlTitle, wx.ID_ANY, "label18")
        self.label19 = wx.StaticText(self.pnlTitle, wx.ID_ANY, "label19")
        self.label20 = wx.StaticText(self.pnlTitle, wx.ID_ANY, "label20")
        self.label21 = wx.StaticText(self.pnlTitle, wx.ID_ANY, "label21")
        self.label22 = wx.StaticText(self.pnlTitle, wx.ID_ANY, "label22")
        self.label23 = wx.StaticText(self.pnlTitle, wx.ID_ANY, "label24")
        self.label24 = wx.StaticText(self.pnlTitle, wx.ID_ANY, "label24")
        self.label25 = wx.StaticText(self.pnlTitle, wx.ID_ANY, "label25")
        self.label26 = wx.StaticText(self.pnlTitle, wx.ID_ANY, "label26")
        self.label27 = wx.StaticText(self.pnlTitle, wx.ID_ANY, "label27")
        self.label28 = wx.StaticText(self.pnlTitle, wx.ID_ANY, "label28")
        self.label29 = wx.StaticText(self.pnlTitle, wx.ID_ANY, "label29")
        self.label30 = wx.StaticText(self.pnlTitle, wx.ID_ANY, "label30")
        self.label31 = wx.StaticText(self.pnlTitle, wx.ID_ANY, "label31")
        self.label32 = wx.StaticText(self.pnlTitle, wx.ID_ANY, "label32")
        self.pnlCanvas = wx.Panel(self.scrollwin, wx.ID_ANY)
        self.pnlInfo = wx.Panel(self.scrollwin, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: myFrame.__set_properties
        self.SetTitle("Tool")
        self.mainframe_statusbar.SetStatusWidths([-1])
        # statusbar fields
        mainframe_statusbar_fields = ["mainframe_statusbar"]
        for i in range(len(mainframe_statusbar_fields)):
            self.mainframe_statusbar.SetStatusText(mainframe_statusbar_fields[i], i)
        self.pnlTitle.SetMinSize((100, 400))
        self.pnlInfo.SetMinSize((100, -1))
        self.scrollwin.SetMinSize((850, 520))
        self.scrollwin.SetScrollRate(1, 1)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: myFrame.__do_layout
        sizer1 = wx.BoxSizer(wx.HORIZONTAL)
        sizerpanel = wx.BoxSizer(wx.HORIZONTAL)
        sizertitle = wx.BoxSizer(wx.VERTICAL)
        sizertitle.Add(self.label1, 100, wx.EXPAND, 0)
        sizertitle.Add(self.label2, 100, wx.EXPAND, 0)
        sizertitle.Add(self.label3, 100, wx.EXPAND, 0)
        sizertitle.Add(self.label4, 100, wx.EXPAND, 0)
        sizertitle.Add(self.label5, 100, wx.EXPAND, 0)
        sizertitle.Add(self.label6, 100, wx.EXPAND, 0)
        sizertitle.Add(self.label7, 100, wx.EXPAND, 0)
        sizertitle.Add(self.label8, 100, wx.EXPAND, 0)
        sizertitle.Add(self.label9, 100, wx.EXPAND, 0)
        sizertitle.Add(self.label10, 100, wx.EXPAND, 0)
        sizertitle.Add(self.label11, 100, wx.EXPAND, 0)
        sizertitle.Add(self.label12, 100, wx.EXPAND, 0)
        sizertitle.Add(self.label13, 100, wx.EXPAND, 0)
        sizertitle.Add(self.label14, 100, wx.EXPAND, 0)
        sizertitle.Add(self.label15, 100, wx.EXPAND, 0)
        sizertitle.Add(self.label16, 100, wx.EXPAND, 0)
        sizertitle.Add(self.label17, 100, wx.EXPAND, 0)
        sizertitle.Add(self.label18, 100, wx.EXPAND, 0)
        sizertitle.Add(self.label19, 100, wx.EXPAND, 0)
        sizertitle.Add(self.label20, 100, wx.EXPAND, 0)
        sizertitle.Add(self.label21, 100, wx.EXPAND, 0)
        sizertitle.Add(self.label22, 100, wx.EXPAND, 0)
        sizertitle.Add(self.label23, 100, wx.EXPAND, 0)
        sizertitle.Add(self.label24, 100, wx.EXPAND, 0)
        sizertitle.Add(self.label25, 100, wx.EXPAND, 0)
        sizertitle.Add(self.label26, 100, wx.EXPAND, 0)
        sizertitle.Add(self.label27, 100, wx.EXPAND, 0)
        sizertitle.Add(self.label28, 100, wx.EXPAND, 0)
        sizertitle.Add(self.label29, 100, wx.EXPAND, 0)
        sizertitle.Add(self.label30, 100, wx.EXPAND, 0)
        sizertitle.Add(self.label31, 100, wx.EXPAND, 0)
        sizertitle.Add(self.label32, 100, wx.EXPAND, 0)
        self.pnlTitle.SetSizer(sizertitle)
        sizerpanel.Add(self.pnlTitle, 0, wx.EXPAND, 0)
        sizerpanel.Add(self.pnlCanvas, 1, wx.EXPAND, 0)
        sizerpanel.Add(self.pnlInfo, 0, wx.EXPAND | wx.ALIGN_RIGHT, 0)
        self.scrollwin.SetSizer(sizerpanel)
        sizer1.Add(self.scrollwin, 1, wx.EXPAND, 0)
        self.SetSizer(sizer1)
        sizer1.Fit(self)
        self.Layout()
        self.Centre()
        # end wxGlade

# end of class myFrame
class MyApp(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        mainframe = myFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(mainframe)
        mainframe.Show()
        return 1

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()